// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wgcodnkqaxqqmxspsgwz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndnY29kbmtxYXhxcW14c3BzZ3d6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyNzcwOTIsImV4cCI6MjA2Njg1MzA5Mn0.iJUgrrAvUHMU4voqqtmMQYu3rQJsj6LZp9Jp5n_TnKs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});